# Generated by Django 5.2.7 on 2026-09-21 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=320)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DELETION_PENDING', 'Deletion pending'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=24)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=64)),
                ('locale', models.CharField(default='en-BD', max_length=16)),
                ('default_currency', models.CharField(default='BDT', max_length=3)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_users',
                'indexes': [models.Index(fields=['status', 'created_at'], name='app_user_status_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'SUSPENDED', 'DELETION_PENDING'])), fields=('email',), name='app_user_live_email_unique'), models.CheckConstraint(condition=models.Q(('status__in', ('ACTIVE', 'SUSPENDED', 'DELETION_PENDING', 'DELETED'))), name='app_user_valid_status'), models.CheckConstraint(condition=models.Q(('default_currency__regex', '^[A-Z]{3}$')), name='app_user_currency_code')],
            },
        ),
        migrations.CreateModel(
            name='UserAuthIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_system', models.CharField(default='SUPABASE', max_length=32)),
                ('issuer', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_identities', to='accounts.appuser')),
            ],
            options={
                'db_table': 'user_auth_identities',
                'indexes': [models.Index(fields=['user'], name='auth_identity_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('issuer', 'subject'), name='auth_identity_issuer_subject_unique')],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_enabled', models.BooleanField(default=False)),
                ('time_reminders_enabled', models.BooleanField(default=False)),
                ('location_reminders_enabled', models.BooleanField(default=False)),
                ('daily_briefing_enabled', models.BooleanField(default=True)),
                ('week_starts_on', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='accounts.appuser')),
            ],
            options={
                'db_table': 'user_preferences',
                'constraints': [models.CheckConstraint(condition=models.Q(('week_starts_on__gte', 0), ('week_starts_on__lte', 6)), name='user_preference_week_start_range')],
            },
        ),
    ]
