# Generated by Django 5.2.7 on 2026-09-21 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super admin')], default='ADMIN', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to='accounts.adminprofile')),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='AdminAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('target_ref_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.appuser')),
                ('actor_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.adminprofile')),
                ('target_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.adminprofile')),
            ],
            options={
                'db_table': 'admin_audit_events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='adminprofile',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('ADMIN', 'SUPER_ADMIN'))), name='admin_profile_valid_role'),
        ),
        migrations.AddIndex(
            model_name='adminauditevent',
            index=models.Index(fields=['actor_admin', 'created_at'], name='audit_actor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditevent',
            index=models.Index(fields=['target_user', 'created_at'], name='audit_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditevent',
            index=models.Index(fields=['action', 'created_at'], name='audit_action_created_idx'),
        ),
    ]
