# Generated by Django 5.2.7 on 2026-09-22 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAiEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trial_limit', models.PositiveIntegerField(default=5)),
                ('trial_used', models.PositiveIntegerField(default=0)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_ai_entitlements',
            },
        ),
        migrations.AddField(
            model_name='userpreference',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='onboarding_tour_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='priority_profile',
            field=models.CharField(choices=[('BALANCED', 'Balanced'), ('STUDY_FIRST', 'Study first'), ('WORK_FIRST', 'Work first')], default='BALANCED', max_length=24),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='profession',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('EMPLOYED', 'Employed'), ('BOTH', 'Both'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='userpreference',
            constraint=models.CheckConstraint(condition=models.Q(('profession__in', ['', 'STUDENT', 'EMPLOYED', 'BOTH', 'OTHER', 'PREFER_NOT_TO_SAY'])), name='user_preference_valid_profession'),
        ),
        migrations.AddConstraint(
            model_name='userpreference',
            constraint=models.CheckConstraint(condition=models.Q(('priority_profile__in', ['BALANCED', 'STUDY_FIRST', 'WORK_FIRST'])), name='user_preference_valid_priority'),
        ),
        migrations.AddField(
            model_name='useraientitlement',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_entitlement', to='accounts.appuser'),
        ),
        migrations.AddConstraint(
            model_name='useraientitlement',
            constraint=models.CheckConstraint(condition=models.Q(('trial_used__lte', models.F('trial_limit'))), name='ai_trial_usage_within_limit'),
        ),
    ]
