# Generated by Django 5.2.7 on 2026-09-23 06:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraientitlement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=12, unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='PENDING', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_requests', to='accounts.appuser')),
            ],
            options={
                'db_table': 'pro_access_requests',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'status'], name='pro_request_user_status_idx'), models.Index(fields=['status', 'created_at'], name='pro_request_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'CONTACTED', 'APPROVED', 'DECLINED'])), name='pro_request_valid_status')],
            },
        ),
    ]
