# Generated by Django 5.2.7 on 2026-09-24 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_proaccessrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroqServerKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('key_encrypted', models.TextField()),
                ('key_hint', models.CharField(blank=True, default='', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('disabled_reason', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trial_keys', to='accounts.adminprofile')),
            ],
            options={
                'db_table': 'groq_server_keys',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
