# Generated by Django 5.2.7 on 2026-09-26 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_groqserverkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroqKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_encrypted', models.TextField()),
                ('key_hint', models.CharField(blank=True, default='', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groq_key', to='accounts.appuser')),
            ],
            options={
                'db_table': 'user_groq_keys',
            },
        ),
    ]
