# Generated by Django 5.2.7 on 2026-09-27 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_groq_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='groqserverkey',
            name='provider',
            field=models.CharField(default='groq', max_length=16),
        ),
        migrations.AddField(
            model_name='usergroqkey',
            name='provider',
            field=models.CharField(default='groq', max_length=16),
        ),
        migrations.AlterField(
            model_name='usergroqkey',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_keys', to='accounts.appuser'),
        ),
        migrations.AddConstraint(
            model_name='usergroqkey',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='user_ai_key_user_provider_unique'),
        ),
    ]
