# Generated by Django 5.2.7 on 2026-09-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_groqserverkey_provider_usergroqkey_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraientitlement',
            name='trial_gemini_limit',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='useraientitlement',
            name='trial_gemini_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='useraientitlement',
            constraint=models.CheckConstraint(condition=models.Q(('trial_gemini_used__lte', models.F('trial_gemini_limit'))), name='ai_trial_gemini_usage_within_limit'),
        ),
    ]
