# Generated by Django 5.2.7 on 2026-09-23 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_proaccessrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TASK_DUE_SOON', 'Task due soon'), ('TASK_COMPLETED', 'Task completed'), ('EXPENSE_INCREASED', 'Expense increased'), ('SYSTEM', 'System'), ('PRO_REQUEST_UPDATE', 'Pro request update')], max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedup_key', models.CharField(blank=True, max_length=128, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.appuser')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='notification_user_created_idx'), models.Index(fields=['user', 'read_at'], name='notification_user_read_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['TASK_DUE_SOON', 'TASK_COMPLETED', 'EXPENSE_INCREASED', 'SYSTEM', 'PRO_REQUEST_UPDATE'])), name='notification_valid_type'), models.UniqueConstraint(fields=('user', 'dedup_key'), name='notification_user_dedup_unique')],
            },
        ),
    ]
