# Generated by Django 5.2.7 on 2026-09-22 10:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_useraientitlement_and_more'),
        ('notes', '0007_note_note_owner_created_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('currency', models.CharField(max_length=3)),
                ('label', models.CharField(max_length=255)),
                ('transaction_at', models.DateTimeField()),
                ('source_kind', models.CharField(choices=[('AI_NOTE', 'AI note'), ('MANUAL', 'Manual'), ('OPENING_BALANCE', 'Opening balance')], default='MANUAL', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_transaction', to='notes.noteitem')),
                ('primary_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_transactions', to='notes.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.appuser')),
            ],
            options={
                'db_table': 'finance_transactions',
                'ordering': ('-transaction_at', '-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-transaction_at'], name='finance_user_at_idx'), models.Index(fields=['user', 'direction', '-transaction_at'], name='finance_user_direction_at_idx'), models.Index(fields=['user', 'currency', '-transaction_at'], name='finance_user_currency_at_idx'), models.Index(fields=['user', 'primary_domain', '-transaction_at'], name='finance_user_domain_at_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('direction__in', ['CREDIT', 'DEBIT'])), name='finance_transaction_valid_direction'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_transaction_positive_amount'), models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='finance_transaction_currency_code'), models.UniqueConstraint(condition=models.Q(('source_kind', 'OPENING_BALANCE')), fields=('user', 'currency'), name='finance_one_opening_balance_per_currency')],
            },
        ),
    ]
