# Generated by Django 5.2.7 on 2026-09-21 07:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='note',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AIProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('ANALYZE', 'Analyze'), ('CONFIRM', 'Confirm / manual organization'), ('EDIT', 'Edit confirmed item')], default='ANALYZE', max_length=10)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('note_revision', models.PositiveIntegerField()),
                ('input_text', models.TextField()),
                ('raw_response', models.TextField(blank=True)),
                ('parsed_response', models.JSONField(blank=True, null=True)),
                ('confirmed_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('EMPTY', 'No items'), ('FAILED', 'Failed'), ('SUPERSEDED', 'Superseded by a newer revision')], max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='notes.note')),
                ('source_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.aiprocessinglog')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='NoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('TASK', 'Task'), ('EVENT', 'Event'), ('EXPENSE', 'Expense'), ('INFORMATION', 'Information')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('normalized_text', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('due_datetime', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('place_hint', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=20)),
                ('importance', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_confirmed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.aiprocessinglog')),
                ('domains', models.ManyToManyField(blank=True, related_name='items', to='notes.domain')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='notes.note')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='aiprocessinglog',
            index=models.Index(fields=['note', '-created_at'], name='log_note_created_idx'),
        ),
        migrations.AddIndex(
            model_name='noteitem',
            index=models.Index(fields=['note', 'is_confirmed'], name='item_note_confirmed_idx'),
        ),
        migrations.AddConstraint(
            model_name='noteitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0), ('amount__isnull', True), _connector='OR'), name='item_nonnegative_amount'),
        ),
        migrations.AddConstraint(
            model_name='noteitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0), ('quantity__isnull', True), _connector='OR'), name='item_nonnegative_quantity'),
        ),
        migrations.AddConstraint(
            model_name='noteitem',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__range', (0, 1)), ('confidence__isnull', True), _connector='OR'), name='item_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='noteitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_type__in', ('TASK', 'EVENT', 'EXPENSE', 'INFORMATION'))), name='item_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='noteitem',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('PENDING', 'COMPLETED', 'CANCELLED', 'ARCHIVED'))), name='item_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='noteitem',
            constraint=models.CheckConstraint(condition=models.Q(('importance__in', ('LOW', 'NORMAL', 'HIGH'))), name='item_valid_importance'),
        ),
    ]
