# Generated by Django 5.2.7 on 2026-09-21 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('notes', '0003_seed_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='app_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.appuser'),
        ),
    ]
