# Generated by Django 5.2.7 on 2026-09-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_systemsetting'),
        ('notes', '0006_make_app_user_sole_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['app_user', '-created_at'], name='note_owner_created_idx'),
        ),
    ]
