# Generated by Django 5.2.7 on 2026-10-01 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0010_correct_confirmed_medicine_obligation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ("-created_at", "-id")},
        ),
    ]
